config/routes.rb
Rails.application.routes.draw do
  resources :lists
  resources :replies
  
  devise_for :users
  root 'top#index'
  get 'top/show'
  resources :events do
    member {get "addition"}
  end
  resources :donuts do
    collection {get "search", "myfavo", "mydonut"}
    member {get "fab","unfab"}
  end
  resources :refrigerators do
    collection {get "delete"}
    member {get "switching"}
  end
  resources :top do
    member {get "follow","nofollow","refollow","norefollow","block"}
  end
  resources :bulletin_boards

  get '*anything' => 'errors#routing_error'
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :refrigerator
  belongs_to :user
  belongs_to :event
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(user_id: current_user.id, refrigerator_id: params[:fid])

    respond_to do |format|
      if @list.save
        format.html { redirect_to bulletin_boards_path, notice: 'リストを新規作成しました。' }
        format.json { render bulletin_boards_path, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'リストを更新しました。' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to bulletin_boards_path, notice: 'リストを削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:refrigerator_id, :user_id, :event_id)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :refrigerator_id %><br>
    <%= f.text_field :refrigerator_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.text_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<div class="font-default">
<h1>リストの編集</h1>

<%= render 'form' %>

<%= link_to '詳細', @list %> |
<%= link_to '戻る', lists_path %>
</div>

app/views/lists/index.html.erb
<div class="font-default">
<p id="notice"><%= notice %></p>

<h1>リスト一覧</h1>

<table>
  <thead>
    <tr>
      <th>冷蔵庫</th>
      <th>利用者</th>
      <th>イベント</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.refrigerator.id %></td>
        <td><%= list.user.username %></td>
        <td><%= list.event %></td>
        <td><%= link_to '詳細', list %></td>
        <td><%= link_to '編集', edit_list_path(list) %></td>
        <td><%= link_to '削除', list, method: :delete, data: { confirm: 'いいんですか？消しますよ？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規リスト', new_list_path %>
</div>

app/views/lists/new.html.erb
<div class="font-default">
<h1>新規リスト</h1>

<%= render 'form' %>

<%= link_to '戻る', lists_path %>
</div>

app/views/lists/show.html.erb
<div class="font-default">
<p id="notice"><%= notice %></p>

<p>
  <strong>Refrigerator:</strong>
  <%= @list.refrigerator %>
</p>

<p>
  <strong>User:</strong>
  <%= @list.user %>
</p>

<p>
  <strong>Event:</strong>
  <%= @list.event %>
</p>

<%= link_to '編集', edit_list_path(@list) %> |
<%= link_to '戻る', lists_path %>
</div>