config/routes.rb
Rails.application.routes.draw do
  resources :lists
  resources :replies
  
  devise_for :users
  root 'top#index'
  get 'top/show'
  resources :events do
    member {get "addition"}
  end
  resources :donuts do
    collection {get "search", "myfavo", "mydonut"}
    member {get "fab","unfab"}
  end
  resources :refrigerators do
    collection {get "delete"}
    member {get "switching"}
  end
  resources :top do
    member {get "follow","nofollow","refollow","norefollow","block"}
  end
  resources :bulletin_boards

  get '*anything' => 'errors#routing_error'
end

app/models/donut.rb
class Donut < ActiveRecord::Base
  belongs_to :user
  has_many :fabs

  attr_reader :image

  validate :check_image



  IMAGE_TYPES =
    { "image/jpeg" => "jpg", "image/gif" => "gif", "image/png" => "png" }

  def extension
    IMAGE_TYPES[content_type]
  end

  def image=(image)
    if image
      self.content_type = image.content_type
      self.data = image.read
      @image = image  #バリデーション用
    end
  end

  def check_image
    if @image
      if data.size > 512.kilobytes
        errors.add(:image, :too_big_image)
      end
      unless IMAGE_TYPES.has_key?(content_type)
        errors.add(:image, :invalid_image)
      end
    end
  end


  class << self
    def search(q)
      rel = all
      if q.present?
        rel = rel.where("title LIKE ? OR material LIKE ?", "%#{q}%", "%#{q}%")
      end
      rel
    end
  end
end

app/controllers/donuts_controller.rb
class DonutsController < ApplicationController
  before_action :set_donut, only: [:show, :edit, :update, :destroy, :picture, :fab, :unfab]

  # GET /donuts
  # GET /donuts.json
  def index
    @donuts = Donut.all
  end

  def myfavo
    @fabs = Fab.where(user_id: current_user.id)
  end

  def mydonut
    @donuts = Donut.where(user_id: current_user.id)
  end


  # GET /donuts/1
  # GET /donuts/1.json
  def show
    if params[:format].in?(["jpg","png","gif"])
      picture
    end
  end

  # GET /donuts/new
  def new
    @donut = Donut.new
  end

  # GET /donuts/1/edit
  def edit
 
  end

  # POST /donuts
  # POST /donuts.json
  def create
    @donut = Donut.new(donut_params)

    respond_to do |format|
      if @donut.save
        format.html { redirect_to @donut, notice: 'レシピの新規作成を完了しました。' }
        format.json { render :show, status: :created, location: @donut }
      else
        format.html { render :new }
        format.json { render json: @donut.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donuts/1
  # PATCH/PUT /donuts/1.json
  def update
    respond_to do |format|
      if @donut.update(donut_params)
        format.html { redirect_to @donut, notice: 'レシピの更新を完了しました。' }
        format.json { render :show, status: :ok, location: @donut }
      else
        format.html { render :edit }
        format.json { render json: @donut.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donuts/1
  # DELETE /donuts/1.json
  def destroy
    @donut.destroy
    respond_to do |format|
      format.html { redirect_to donuts_url, notice: 'レシピの削除が完了しました。' }
      format.json { head :no_content }
    end
  end


  def search
    @donuts = Donut.search(params[:q])
    render "index"
  end

  def fab
    Fab.new(donut_id: @donut.id, user_id: current_user.id).save
    redirect_to :back
  end

  def unfab
    Fab.find_by(donut_id: @donut.id, user_id: current_user.id).destroy
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donut
      @donut = Donut.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donut_params
      params.require(:donut).permit(:user_id, :title, :material, :image)
    end

    #画像送信（picture_donut_path(@donut)でアクセス）
    def picture
      if @donut.data.present?
        send_data(@donut.data, :type => @donut.content_type, :disposition => 'inline')
      end
    end
end

app/helpers/donuts_helper.rb
module DonutsHelper
end

app/views/donuts/_form.html.erb
<%= form_for(@donut) do |f| %>
  <% if @donut.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donut.errors.count, "error") %> このレシピは保存出来ませんでした。:</h2>

      <ul>
      <% @donut.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :material %><br>
    <%= f.text_area :material %>
  </div>
  <div class="field">

    <meta charset="UTF-8">
  　<link href="css/picStyle.css" rel="stylesheet" type="text/css">
  　<link href="css/bootstrap.min.js" type="text/css"></link>
    <script type="text/javascript" src="./javascript/jquery-3.0.0.minå.js"></script>
　  <script type="text/javascript" src="javascript/picExh.js"></script>
  　<script type="text/javascript" src="javascript/bootstrap.min.js"></script>

    <%= f.label :image %><br>
    <%= donut_image_tag @donut , width: 150 %><br>

    <input type="hidden" name="MAX_FILE_SIZE" value="0" />
    <%= f.file_field :image ,:id =>"0", :onchange => "change();" %>

  </div>

  <div class="actions">
    <% if current_page?(new_donut_path) %>
      <%= f.submit "新規作成"%>
    <% else %>
      <%= f.submit "レシピの更新"%>
    <% end %>
  </div>
<% end %>

app/views/donuts/edit.html.erb
<div class="font-default">
<h1>レシピの編集</h1>

<%= render 'form' %>

<%= link_to '詳細', @donut %> |
<%= link_to '戻る', donuts_path %>
</div>

app/views/donuts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>レシピ</h1>
<%= render 'shared/donuts_header' %>
<div class="right">
	<%= form_tag :search_donuts, method: :get do %>
  	<p><%= text_field_tag "q", params[:q] %><%= submit_tag "検索" %></p>
	<% end %>
	<%= link_to 'レシピ投稿', new_donut_path %>
</div>

<table class="donutslist">
  <% @donuts.each do |donut| %>
    <tr>
      <td><%= donut_image_tag donut , width: 160, height:160 %></td>
      <td style="width: 300px; word-break: break-all; vertical-align: top; border-bottom-style: dashed; border-color: orange;">
      	<h2><%= link_to "#{donut.title}", donut %></h2>
      	<%= donut.material %>
      </td>
    </tr>
  <% end %>
</table>

app/views/donuts/mydonut.html.erb
<div class="font-default">
<p id="notice"><%= notice %></p>

<h1>編集・投稿</h1>

<%= render 'shared/donuts_header' %>

<div class="right">
	<%= link_to 'レシピ投稿', new_donut_path %>
</div>

<table>
  <% @donuts.each do |donut| %>
    <tr>
      <td><%= donut_image_tag donut , width: 100 %></td>
      <td style="width: 300px; word-break: break-all; vertical-align: top; border-bottom-style: dashed; border-color: orange;"><h2><%= link_to "#{donut.title}", donut %></h2><%= donut.material %></td>
      <td><%= link_to '編集', edit_donut_path(donut) %></td>
      <td><%= link_to '削除', donut_path(donut), method: :delete %></td>
    </tr>
    </tr>
  <% end %>
</table>

<br>
</div>

app/views/donuts/myfavo.html.erb
<div class="font-default">
<p id="notice"><%= notice %></p>

<h1>お気に入り</h1>

<%= render 'shared/donuts_header' %>

<table>
  <% @fabs.each do |fab| %>
    <tr>
      <td><%= donut_image_tag fab.donut , width: 100 %></td>
      <td style="width: 300px; word-break: break-all; vertical-align: top; border-bottom-style: dashed; border-color: orange;"><h2><%= link_to "#{fab.donut.title}", fab.donut %></h2><%= fab.donut.material %></td>
      <td><h3><%= link_to '[はずす]', unfab_donut_path(fab.donut) %></h3></td>
    </tr>
  <% end %>
</table>

<br>
</div>

app/views/donuts/new.html.erb
<div class="font-default">
<h1>新規レシピ投稿</h1>

<%= render 'form' %>

<%= link_to '戻る', donuts_path %>
</div>

app/views/donuts/show.html.erb
<div class="font-default">
<p id="notice"><%= notice %></p>

<%= render 'shared/donuts_header' %>

<table>
	<tr>
	  <td colspan="2"><h1><strong><%= @donut.title %></strong></h1></td>
	</tr>
	<tr>
		<td rowspan="2"><%= donut_image_tag @donut , width: 250 %></td>
		<td><h3>○材料○</h3></td>
	</tr>
	<tr>
		<td><%= simple_format(@donut.material) %></td>
	</tr>
</table>
<% if Fab.find_by(donut_id: @donut.id, user_id: current_user.id) %>
	<h4><%= link_to 'お気に入りからはずす', unfab_donut_path(@donut) %></h4>
<% else %>
	<h4><%= link_to 'お気に入りに追加', fab_donut_path(@donut) %></h4>
<% end %>

</div>