config/routes.rb
Rails.application.routes.draw do
  resources :lists
  resources :replies
  
  devise_for :users
  root 'top#index'
  get 'top/show'
  resources :events do
    member {get "addition"}
  end
  resources :donuts do
    collection {get "search", "myfavo", "mydonut"}
    member {get "fab","unfab"}
  end
  resources :refrigerators do
    collection {get "delete"}
    member {get "switching"}
  end
  resources :top do
    member {get "follow","nofollow","refollow","norefollow","block"}
  end
  resources :bulletin_boards

  get '*anything' => 'errors#routing_error'
end

app/views/shared/_donuts_header.html.erb
<script src="tabs.js"></script>
<ul class="tab2">
  <section class="color-7">
    <nav class="cl-effect-4">
      <li class="select"><h3><%= link_to 'レシピ一覧', donuts_path %></h3></li>
      <li class="select"><h3><%= link_to 'お気に入り', myfavo_donuts_path %></h3></li>
      <li class="select"><h3><%= link_to 'レシピ編集', mydonut_donuts_path %></h3></li>
    </nav>
  </section>
</ul>

app/views/shared/_header.html.erb
<nav>
  <div id="modal-content">
  <% if user_signed_in? %>
    <ul id="nav">
    <li><strong><%= link_to current_user.username+'さん', top_show_path %></strong></li>
    <li><%= link_to '冷蔵庫', refrigerators_path %></li>
    <li><%= link_to '掲示板', bulletin_boards_path %></li>
    <li><%=link_to "レシピ", donuts_path %></li>
    <!--<li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, data: { confirm: 'ログアウトしますか？' } %></li>-->
    <li><%= link_to image_tag('a.png'), destroy_user_session_path, method: :delete, data: { confirm: 'ログアウトしますか？' } %></li>
    </ul>
    <br />
  <% end %>

  <p><a id="modal-close" class="button-link">閉じる</a></p>
  <!-- モーダルウィンドウのコンテンツ終了 -->
  </div>

  <p><a id="modal-open"><%= image_tag("modal.png") %></a></p>
  <!-- ここまでモーダルウィンドウ -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="modal.js"></script>
</nav>

app/views/shared/_top_link.html.erb
<%=link_to "トップへ戻る", top_show_path %>

app/views/shared/_user_header.html.erb
<script src="tabs.js"></script>
<ul class="tab2">
  <section class="color-7">
    <nav class="cl-effect-4">
      <li class="select"><h3><%= link_to 'フレンド', donuts_path %></h3></li>
      <li><h3><%= link_to 'ユーザー情報', myfavo_donuts_path %></h3></li>
      <li><h3><%= link_to '利用者一覧', mydonut_donuts_path %></h3></li>
    </nav>
  </section>
</ul>