config/routes.rb
Rails.application.routes.draw do
  resources :lists
  resources :replies
  
  devise_for :users
  root 'top#index'
  get 'top/show'
  resources :events do
    member {get "addition"}
  end
  resources :donuts do
    collection {get "search", "myfavo", "mydonut"}
    member {get "fab","unfab"}
  end
  resources :refrigerators do
    collection {get "delete"}
    member {get "switching"}
  end
  resources :top do
    member {get "follow","nofollow","refollow","norefollow","block"}
  end
  resources :bulletin_boards

  get '*anything' => 'errors#routing_error'
end

app/models/event.rb
class Event < ActiveRecord::Base
	#sをつけよう
	has_many :refrigerators
	has_many :lists
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :addition]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @myrefri = Refrigerator.where(user_id: current_user.id).where(event_id: nil)
  end

  # GET /events/new
  def new
    @event = Event.new
    @myrefri = Refrigerator.where(user_id: current_user.id).where(event_id: nil)
  end

  # GET /events/1/edit
  def edit
    @myrefri = Refrigerator.where(user_id: current_user.id).where(event_id: [nil, @event.id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)


    respond_to do |format|
      if @event.save
        params[:refri][:id].each do |refrigerator_id|
          @refrigerator = Refrigerator.find(refrigerator_id)
          @refrigerator.update_attributes(event_id: @event.id)
        end
        format.html { redirect_to @event, notice: '新しいイベントを作成しました。' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        #元の関連を削除した上で更新
        Refrigerator.where(user_id: current_user.id, event_id: @event.id).each do |re|
          re.update_attributes(event_id: nil)
        end
        params[:refri][:id].each do |refrigerator_id|
          @refrigerator = Refrigerator.find(refrigerator_id)
          @refrigerator.update_attributes(event_id: @event.id)
        end
        format.html { redirect_to @event, notice: 'イベントを更新しました。' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'イベントを削除しました。' }
      format.json { head :no_content }
    end
  end

  def addition
    @refrigerator = Refrigerator.find(params[:refri])
    if params[:dele]
      @refrigerator.update_attributes(event_id: nil)
    else
      @refrigerator.update_attributes(event_id: @event.id)
    end
    redirect_to action: "show"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:refrigerator_id, :place, :date, :upper_num, :lower_num)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_addition.html.erb
<% @myrefri.each do |refrigerator| %>
    <%= refrigerator.name %>
    <%= link_to '追加', addition_event_path(eve, refri: refrigerator.id) %><br>
<% end %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% @myrefri.each do |refrigerator| %>
      <%= check_box_tag 'refri[id][]', refrigerator.id, refrigerator.event %>
      <%= refrigerator.name %><br>
    <% end %>
  </div>
  <%= @myrefri %>
  <div class="field">
    <%= f.label :place, "場所" %><br>
    <%= f.text_area :place %>
  </div>
  <div class="field">
      <%= f.label :date , "日時" %><br>
      <%= raw sprintf(
              f.date_select(
                  :date,
                  use_month_numbers: true,
                  start_year:        (Time.now.year),
                  end_year:          (Time.now.year + 20),
                  default:           Date.new(Time.now.year, 1, 1),
                  date_separator:    '%s'), '年 ', '月 ') + '日' %>
    </div>
  <div class="field">
    <%= f.label :upper_num, "最大人数" %><br>
    <%= f.number_field :upper_num %>
  </div>
  <div class="field">
    <%= f.label :lower_num, "最低人数" %><br>
    <%= f.number_field :lower_num %>
  </div>
  <div class="actions">
    <% if current_page?(new_event_path) %>
      <%= f.submit "新規作成"%>
    <% else %>
      <%= f.submit "イベントの更新"%>
    <% end %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>イベントの変更</h1>

<%= render 'form' %>

<%= link_to '詳細', @event %> |
<%= link_to '戻る', events_path %>

app/views/events/index.html.erb
<div>
<h1>イベントリスト</h1>

<div class="right">
  <%= link_to '新規イベント', new_event_path %>
</div>

<table class="tab_table">
  <thead>
    <tr>
      <th>場所</th>
      <th>日付</th>
      <th>最大人数</th>
      <th>最低人数</th>
      <th colspan="3">操作</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.place %></td>
        <td><%= event.date.to_date %></td>
        <td><%= event.upper_num %></td>
        <td><%= event.lower_num %></td>
        <td><%= link_to '詳細', event %></td>
        <td><%= link_to '編集', edit_event_path(event) %></td>
        <td><%= link_to '削除', event, method: :delete, data: { confirm: 'イベント、消しますよ？' } %></td>
        <td>
          <% if event.refrigerators.first.user != current_user %><!--もしもイベ主催者でなかったら...by菅谷-->
            <% if @list = List.find_by(event_id: event.id, user_id: current_user.id, delete_flag: false) %>
              <%= link_to '[参加取消]', list_path(@list), method: :delete %>
            <% else %>
              <%= link_to '[参加]', lists_path(eid: event.id), method: :post %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/events/new.html.erb
<div>
	<h1>新しくイベントを作る</h1>
	<%= render 'form' %>
	<div class="right">
		<%= link_to 'やっぱりやめる', events_path %>
	</div>
</div>

app/views/events/show.html.erb
<div>

<p>
  <strong>食材:</strong>
  <% @event.refrigerators.each do |re| %>
    <br><%= re.name %> (by <%= re.user.username%>)
    <% if re.user == current_user %>
      <%= link_to '[取消]', addition_event_path(@event, refri: re.id, dele: 1) %>
    <% end %>
  <% end %>

  <% if List.find_by(user_id: current_user.id, event_id: @event.id, delete_flag: false) %>
    <br><%= link_to '[食材追加]', event_path(add: "a") %>
  <% end %>
  <% if params[:add] %>
    <br><%= render "addition" , eve: @event %>
  <% end %>
</p>

<p>
  <strong>場所:</strong>
  <%= @event.place %>
</p>

<p>
  <strong>参加者</strong>
  <%= @event.refrigerators.first.user.username %>
  <% List.where(event_id: @event.id, delete_flag: false).each do |list| %>
    ・<%= list.user.username %>
  <% end %>
</p>

<p>
  <strong>日時:</strong>
  <%= @event.date.to_date %>
</p>

<p>
  <strong>最大人数:</strong>
  <%= @event.upper_num %>
</p>

<p>
  <strong>最低人数:</strong>
  <%= @event.lower_num %>
</p>

<%= link_to '変更', edit_event_path(@event) %> |
<%= link_to '戻る', events_path %>
</div>